import { Guest, NodeWorker, Target, WorkerLike } from './types';
export declare function isWorker(): boolean;
export declare function isNodeEnv(): boolean;
export declare function isIframe(): boolean;
export declare function extractMethods(obj: any): Record<string, (...args: any) => any>;
export declare function getOriginFromURL(url: string | null): string | null;
export declare function get(obj: any, path: string | Array<string | number>, defaultValue?: any): any;
export declare function set(obj: any, path: string | (string | number)[], value: any): any;
export declare function generateId(length?: number): string;
export declare function getTargetHost(): any;
export declare function postMessageToTarget(target: Target, message: any, origin?: string, transferables?: Transferable[]): void;
export declare function isNodeWorker(guest: Guest | Target): guest is NodeWorker;
export declare function isWorkerLike(guest: Guest): guest is WorkerLike;
export declare function addEventListener(target: Target, event: string, handler: EventListenerOrEventListenerObject): void;
export declare function removeEventListener(target: Target, event: string, handler: EventListenerOrEventListenerObject): void;
export declare function getEventData(event: any): any;
